config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :tasks

  resources :users

  root 'tasks#index'

  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :delete]
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks do
  post 'toggle_completion', on: :member
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	has_many :groups, through: :task_to_groups
	has_many :task_to_groups, dependent: :destroy
	validates :name, presence: true
	validates :description, presence: true
	validates :user, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_logged_in, only: [:edit, :update, :destroy, :index]

  def toggle_completion
    task=Task.find(params[:id])
    task.update_attribute :completed, (not task.completed)
    redirect_to :back
  end


  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = Task.all
    @tasks = current_user.tasks.includes(:groups).order(completed: :asc, priority: :desc)

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user=current_user

    #byebug
    respond_to do |format|
      if @task.save
        params[:task][:groups].select{ |m| m.present? }.map{ |m| m.to_i }.map{ |m| Group.find(m) }.each{ |g| TaskToGroup.create(task: @task, group: g) }
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        params[:task][:groups].select{ |m| m.present? }.map{ |m| m.to_i }.map{ |m| Group.find(m) }.each{ |g| TaskToGroup.create(task: @task, group: g) }
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      #testataan voiko groupseja massasijoittaa
      params.require(:task).permit(:name, :description, :completed, :priority, :groups)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= collection_select(:task, :groups, current_user.groups, :id, :name, {}, {multiple:true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% if @tasks.empty? %>
<p>You don't have any tasks at the moment. Create one by clicking the button below.</p>
<% end %>
<% @tasks.each do |t| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <% if t.completed? %>
        <span class="glyphicon glyphicon-ok"></span>
      <% else %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>
      <%= t.name %>
      <span class="badge">
      <%= t.priority %>
      </span>
    </div>
    <div class="panel-body">
    <%= t.description %>
    </div>
      <ul class="list-inline" style="margin-left: 10px;">
      <% unless t.groups.empty? %>
        <% t.groups.each do |g| %>
          <li>
            <%= link_to g, g, class:"btn btn-xs btn-default" %>
          </li>
        <% end %>
      <% end %>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe , edit_task_path(t), class:"btn btn-xs btn-primary" %>
        </li>
        <li>
          <% if t.completed? %>
          <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe , toggle_completion_task_path(t.id), method: :post, class:"btn btn-xs btn-danger" %>
          <% else %>
            <%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe , toggle_completion_task_path(t.id), method: :post, class:"btn btn-xs btn-success" %>
          <% end %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, t, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-default" %>
        </li>
      </ul>
  </div>
<% end %>



<%= link_to 'New Task', new_task_path, class:"btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>