config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :tasks

  resources :users

  root 'tasks#index'

  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :delete]
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks do
  post 'toggle_completion', on: :member
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :tasks, through: :task_to_groups
	has_many :task_to_groups, dependent: :destroy
	belongs_to :user

	def to_s
		self.name
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    #@groups = Group.all
    @groups = current_user.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @tasks=@group.tasks.includes(:groups).order(completed: :asc, priority: :desc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user=current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      group_params[:user_id]=current_user.id #toimiikohan?
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.includes(:tasks).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.user_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1>
<%= @group.name %>
</h1>

<%# copypastaa, orginal task/index.html.erb %>
<% @tasks.each do |t| %>
	<% @t=t %>
	<%= render 'layouts/task' %>
<% end %>
<% if @tasks.empty? %>
<p>No tasks in this group.</p>
<% end %>

<ul class="list-inline">
        <li>
        	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, tasks_path, class:"btn btn-default btn-xs" %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-pencil"></span> edit'.html_safe , edit_group_path(@group), class:"btn btn-xs btn-default" %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-trash"></span> remove'.html_safe, @group, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-danger" %>
        </li>
</ul>