config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :tasks

  resources :users

  root 'tasks#index'

  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :delete]
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks do
  post 'toggle_completion', on: :member
  end

end

app/views/layouts/_login_form.html.erb
<% if current_user.nil? %>
    <%= form_tag session_path, class:"form-inline" do %>
      <span class="input-group input-group-sm">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
        <!--<input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1"> -->
        <%= text_field_tag :username, params[:username], placeholder:"username", class:"form-control" %>
      </span>
      <span class="input-group input-group-sm">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
        <%= password_field_tag :password, params[:password], placeholder:"password", class:"form-control" %>
      </span>
      <%= submit_tag "Log in", class:'btn btn-primary btn-sm' %>
      <% end %>
<% else %>
  <% link_text = "logout #{current_user}" %>
  <%= link_to link_text, logout_path, method: :delete %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%#<li><%= render 'layouts/login_form' %><%#</li> %>
<% if current_user %>
<li role="presentation" class="dropdown">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
		groups <span class="caret"></span>
	</a>
	<ul class="dropdown-menu" role="menu">
		<% current_user.groups.each do |g| %>
			<li><%= link_to g.name, g %></li>
		<% end %>
		<% unless current_user.groups.empty? %>
			<li role="presentation" class="divider"></li>
		<% end %>
		<li><%= link_to 'new group', new_group_path %></li>
	</ul>
</li>
<li><%= link_to "logout #{current_user}", logout_path, method: :delete %></li>
<li><%= link_to "change password", edit_user_path(current_user) %></li>
<% end %>

app/views/layouts/_task.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">
      <% if @t.completed? %>
        <span class="glyphicon glyphicon-ok"></span>
      <% else %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>
      <%= @t.name %>
      <span class="badge">
      <%= @t.priority %>
      </span>
    </div>
    <div class="panel-body">
    <%= @t.description %>
    </div>
      <ul class="list-inline" style="margin-left: 10px;">
      <% unless @t.groups.empty? %>
        <% @t.groups.each do |g| %>
          <li>
            <%= link_to g, g, class:"btn btn-xs btn-default" %>
          </li>
        <% end %>
      <% end %>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe , edit_task_path(@t), class:"btn btn-xs btn-primary" %>
        </li>
        <li>
          <% if @t.completed? %>
          <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe , toggle_completion_task_path(@t.id), method: :post, class:"btn btn-xs btn-danger" %>
          <% else %>
            <%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe , toggle_completion_task_path(@t.id), method: :post, class:"btn btn-xs btn-success" %>
          <% end %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, @t, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-default" %>
        </li>
      </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Muistilista" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Muistilista" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>